# Generated by Django 4.1.7 on 2023-03-13 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nftprod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='nft',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='nftprod.nft'),
        ),
    ]
