# Generated by Django 4.1.7 on 2023-03-13 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nftprod', '0002_alter_ownership_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
