# Generated by Django 4.1.7 on 2023-03-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftprod', '0002_nft_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
