# Generated by Django 4.1.7 on 2023-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftprod', '0003_alter_ownership_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(fields=('user', 'nft'), name='unique_ownership'),
        ),
    ]
