# Generated by Django 4.1.7 on 2023-03-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftprod', '0003_category_is_active_collection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
