# Generated by Django 4.1.7 on 2023-03-13 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nftprod', '0005_alter_nft_id_alter_ownership_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ownership',
            name='unique_ownership',
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nft_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
