# Generated by Django 4.1.7 on 2023-03-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftprod', '0005_currency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
