# Generated by Django 4.1.7 on 2023-03-13 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nftprod', '0006_remove_ownership_unique_ownership_alter_nft_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='owner',
        ),
        migrations.AddField(
            model_name='nft',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nft_creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
